// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default'];
    EAvatar: typeof import('eurus-ui')['EAvatar'];
    EBreadcrumb: typeof import('eurus-ui')['EBreadcrumb'];
    EButton: typeof import('eurus-ui')['EButton'];
    ECarousel: typeof import('eurus-ui')['ECarousel'];
    ECarouselItem: typeof import('eurus-ui')['ECarouselItem'];
    ECheckbox: typeof import('eurus-ui')['ECheckbox'];
    EDatePicker: typeof import('eurus-ui')['EDatePicker'];
    EDateRangePicker: typeof import('eurus-ui')['EDateRangePicker'];
    EDialog: typeof import('eurus-ui')['EDialog'];
    EDivider: typeof import('eurus-ui')['EDivider'];
    EDrawer: typeof import('eurus-ui')['EDrawer'];
    EInput: typeof import('eurus-ui')['EInput'];
    EPagination: typeof import('eurus-ui')['EPagination'];
    ERadio: typeof import('eurus-ui')['ERadio'];
    ERadioGroup: typeof import('eurus-ui')['ERadioGroup'];
    ERate: typeof import('eurus-ui')['ERate'];
    ESelect: typeof import('eurus-ui')['ESelect'];
    ESelectDown: typeof import('eurus-ui')['ESelectDown'];
    ESwitch: typeof import('eurus-ui')['ESwitch'];
    ETab: typeof import('eurus-ui')['ETab'];
    ETabPane: typeof import('eurus-ui')['ETabPane'];
    ETabs: typeof import('eurus-ui')['ETabs'];
    ETabsPane: typeof import('eurus-ui')['ETabsPane'];
    ETag: typeof import('eurus-ui')['ETag'];
    ETextarea: typeof import('eurus-ui')['ETextarea'];
    ETooltip: typeof import('eurus-ui')['ETooltip'];
    ETree: typeof import('eurus-ui')['ETree'];
    EUpload: typeof import('eurus-ui')['EUpload'];
    Footer: typeof import('./src/components/Footer.vue')['default'];
    README: typeof import('./src/components/README.md')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('eurus-ui')['vLoading'];
  }
}
