// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./src/components/Counter.vue')['default'];
    EButton: typeof import('eurus-ui')['EButton'];
    ECheckbox: typeof import('eurus-ui')['ECheckbox'];
    EDatePicker: typeof import('eurus-ui')['EDatePicker'];
    EDialog: typeof import('eurus-ui')['EDialog'];
    EDivider: typeof import('eurus-ui')['EDivider'];
    EDrawer: typeof import('eurus-ui')['EDrawer'];
    EInput: typeof import('eurus-ui')['EInput'];
    ERate: typeof import('eurus-ui')['ERate'];
    ESwitch: typeof import('eurus-ui')['ESwitch'];
    EUpload: typeof import('eurus-ui')['EUpload'];
    Footer: typeof import('./src/components/Footer.vue')['default'];
    README: typeof import('./src/components/README.md')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('eurus-ui')['vLoading'];
  }
}
