// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AlgoliaSearchBox: typeof import('./.vitepress/theme/components/AlgoliaSearchBox.vue')['default']
    ArrowLeft: typeof import('./.vitepress/theme/components/icons/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./.vitepress/theme/components/icons/ArrowRight.vue')['default']
    BooleanDisplay: typeof import('./.vitepress/theme/components/BooleanDisplay.vue')['default']
    CarbonEdit: typeof import('~icons/carbon/edit')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    ClientOnly: typeof import('./.vitepress/components/ClientOnly.ts')['default']
    CodeDemo: typeof import('./.vitepress/components/CodeDemo.vue')['default']
    CodeDemos: typeof import('./.vitepress/components/CodeDemos.vue')['default']
    Content: typeof import('./.vitepress/components/Content.ts')['default']
    Counter: typeof import('./.vitepress/components/Counter.vue')['default']
    DarkModeSwitch: typeof import('./.vitepress/theme/components/DarkModeSwitch.vue')['default']
    Debug: typeof import('./.vitepress/components/Debug.vue')['default']
    DemoContainer: typeof import('./.vitepress/theme/components/DemoContainer.vue')['default']
    EditLink: typeof import('./.vitepress/theme/components/EditLink.vue')['default']
    Home: typeof import('./.vitepress/theme/components/Home.vue')['default']
    HomeFeatures: typeof import('./.vitepress/theme/components/HomeFeatures.vue')['default']
    HomeFooter: typeof import('./.vitepress/theme/components/HomeFooter.vue')['default']
    HomeHero: typeof import('./.vitepress/theme/components/HomeHero.vue')['default']
    'La:codepen': typeof import('~icons/la/codepen')['default']
    LangSwitch: typeof import('./.vitepress/theme/components/LangSwitch.vue')['default']
    LastUpdated: typeof import('./.vitepress/theme/components/LastUpdated.vue')['default']
    Moon: typeof import('./.vitepress/theme/components/icons/Moon.vue')['default']
    NavBar: typeof import('./.vitepress/theme/components/NavBar.vue')['default']
    NavBarTitle: typeof import('./.vitepress/theme/components/NavBarTitle.vue')['default']
    NavDropdownLink: typeof import('./.vitepress/theme/components/NavDropdownLink.vue')['default']
    NavDropdownLinkItem: typeof import('./.vitepress/theme/components/NavDropdownLinkItem.vue')['default']
    NavLink: typeof import('./.vitepress/theme/components/NavLink.vue')['default']
    NavLinks: typeof import('./.vitepress/theme/components/NavLinks.vue')['default']
    NextAndPrevLinks: typeof import('./.vitepress/theme/components/NextAndPrevLinks.vue')['default']
    Note: typeof import('./.vitepress/theme/components/Note.vue')['default']
    OutboundLink: typeof import('./.vitepress/theme/components/icons/OutboundLink.vue')['default']
    Page: typeof import('./.vitepress/theme/components/Page.vue')['default']
    PageFooter: typeof import('./.vitepress/theme/components/PageFooter.vue')['default']
    'Ph:code': typeof import('~icons/ph/code')['default']
    'Ph:copyThin': typeof import('~icons/ph/copy-thin')['default']
    'Ri:englishInput': typeof import('~icons/ri/english-input')['default']
    SideBar: typeof import('./.vitepress/theme/components/SideBar.vue')['default']
    SideBarLink: typeof import('./.vitepress/theme/components/SideBarLink.ts')['default']
    SideBarLinks: typeof import('./.vitepress/theme/components/SideBarLinks.vue')['default']
    Sun: typeof import('./.vitepress/theme/components/icons/Sun.vue')['default']
    ThemeGallery: typeof import('./.vitepress/theme/components/ThemeGallery.vue')['default']
    ThemeInfo: typeof import('./.vitepress/theme/components/ThemeInfo.vue')['default']
    ToggleSideBarButton: typeof import('./.vitepress/theme/components/ToggleSideBarButton.vue')['default']
    'Uil:letterChineseA': typeof import('~icons/uil/letter-chinese-a')['default']
  }
}

export {}
