/*
 * @Author: jiangxd
 * @Date: 2022-06-04 14:56:12
 * @LastEditTime: 2022-06-04 14:59:32
 * @LastEditors: jiangxd
 * @Description:
 * @FilePath: /eurus-ui/docs/components.d.ts
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeDemo: typeof import('./.vitepress/components/CodeDemo.vue')['default']
  }
}

export {}
